server:
  port: 8281

spring:
  application:
    name: org-service

  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  sql:
    init:
      data-locations: classpath:db/local/data.sql
