eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVER_HOSTNAME:localhost}:8761/eureka/

spring:
  cloud:
    inetutils:
      preferredNetworks:
        - 192.168

resilience4j:
  retry:
    instances:
      throwingException:
        maxRetryAttempts: 2
        waitDuration: 2s
        retryExceptions:
          - java.lang.Exception