server:
  port: 8181

spring:
  application:
    name: orcid-service

  cloud:
    circuitbreaker:
      bulkhead:
        resilience4j:
          enabled: true
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}

  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        minimum-number-of-calls: 10
        sliding-window-type: TIME_BASED
        sliding-window-size: 10
        wait-duration-in-open-state: 50s
        permitted-number-of-calls-in-half-open-state: 3

    instances:
      orcid:
        base-config: default
        wait-duration-in-open-state: 51s

  timelimiter:
    configs:
      default:
        timeoutDuration: 2s
        cancelRunningFuture: true

    instances:
      orcid:
        base-config: default
  thread-pool-bulkhead:
    configs:
      default:
        max-thread-pool-size: 1
        core-thread-pool-size: 1

    instances:
      orcid:
        base-config: default

  bulkhead:
    configs:
      default:
        max-concurrent-calls: 10

    instances:
      orcid:
        base-config: default

app:
  gateways:
    orcid:
      host: pub.orcid.org
      version: v2.1
      url: https://${app.gateways.orcid.host}/${app.gateways.orcid.version}

  url:
    check-server-status: ${app.gateways.orcid.url}/status
    fetch-record-details: ${app.gateways.orcid.url}/{orcid}
